# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'LeaveApplication' do
  pod 'Alamofire', '~> 3.2'
  pod 'SwiftyJSON', '~> 2.3'
  pod 'IQKeyboardManagerSwift', '~> 4.0'
  pod 'Font-Awesome-Swift', '~> 1.4.5'
  pod 'KDCircularProgress', '~> 1.3'
  pod 'SwiftHEXColors'
  pod "PKHUD"
end

target 'LeaveApplicationTests' do

end

target 'LeaveApplicationUITests' do

end

